const fs = require('fs');
const path = require('path');

let allKeys = new Set();
function walk(dir) {
  const files = fs.readdirSync(dir);
  for (const file of files) {
    const fullPath = path.join(dir, file);
    if (fs.statSync(fullPath).isDirectory()) {
      walk(fullPath);
    } else if (fullPath.endsWith('.html') || fullPath.endsWith('.ts')) {
      const content = fs.readFileSync(fullPath, 'utf8');
      const regex = /'([^']+)'\s*\|\s*t/g;
      let match;
      while ((match = regex.exec(content)) !== null) {
        allKeys.add(match[1].trim());
      }
    }
  }
}
walk('src/app');

const manualKeys = [
  'Admin Dashboard', 'Employee Dashboard', 'Company Announcements', 'System Alert', 
  'Dashboard', 'My Profile', 'Employees', 'Leave Requests', 'Attendance', 'Salaries', 
  'System Control', 'Departments', 'Positions', 'Register User', 'Logout', 'HR Management',
  'Urgent', 'High', 'Normal', 'Pending', 'Approved', 'Rejected',
  'Jan', 'Feb', 'Mar', 'Apr', 'May_short', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec',
  'All Types', 'All Statuses', 'All Years', 'All Months', 'System Admin'
];
manualKeys.forEach(k => allKeys.add(k));

const dictionary = {
  'Dashboard': 'الرئيسية',
  'My Profile': 'ملفي الشخصي',
  'Employees': 'الموظفون',
  'Leave Requests': 'طلبات الإجازة',
  'Attendance': 'الحضور والانصراف',
  'Salaries': 'مسيرات الرواتب',
  'System Control': 'إدارة النظام',
  'Departments': 'الأقسام الإدارية',
  'Positions': 'المسميات الوظيفية',
  'Register User': 'تسجيل مستخدم جديد',
  'Logout': 'تسجيل الخروج',
  'HR Management': 'إدارة الموارد البشرية',
  'Settings': 'الإعدادات',
  'Theme': 'المظهر',
  'Dark Mode': 'الوضع الداكن',
  'Light Mode': 'الوضع الفاتح',
  'Language': 'اللغة',
  'Notifications': 'الإشعارات',
  'No new notifications': 'لا توجد إشعارات جديدة',
  'New': 'جديد',
  'System Alert': 'تنبيه النظام',
  'Install App': 'تثبيت التطبيق',
  'Overall': 'الإجمالي',
  'Admin Dashboard': 'لوحة تحكم الإدارة',
  'Employee Dashboard': 'لوحة تحكم الموظف',
  'Welcome back': 'مرحباً بك مجدداً',
  'Total Employees': 'إجمالي الموظفين',
  'Attendance Rate': 'نسبة الحضور',
  'Pending Leaves': 'الإجازات المعلقة',
  'Next Payday': 'موعد صرف الراتب القادم',
  'Recent Leave Requests': 'أحدث طلبات الإجازة',
  'Leave Distribution': 'توزيع الإجازات',
  'Annual': 'سنوية',
  'Sick': 'مرضية',
  'Emergency': 'طارئة',
  'Unpaid': 'بدون راتب',
  'Annual Leave Balance': 'رصيد الإجازات السنوية',
  'Days Remaining': 'أيام متبقية',
  'My Salary': 'راتبي',
  'My Pending Leaves': 'طلبات إجازاتي المعلقة',
  'All Leave Requests': 'جميع طلبات الإجازة',
  'My Leave Requests': 'طلبات إجازاتي',
  'Manage and track time-off requests effectively': 'إدارة ومتابعة طلبات الإجازات والمغادرات بفعالية',
  'Search by name, ID, or reason...': 'ابحث بالاسم، أو الرقم الوظيفي، أو السبب...',
  'Filter Options': 'خيارات التصفية',
  'Leave Type': 'نوع الإجازة',
  'All Types': 'جميع الأنواع',
  'Status': 'الحالة',
  'All Statuses': 'جميع الحالات',
  'Pending': 'قيد المراجعة',
  'Approved': 'معتمدة',
  'Rejected': 'مرفوضة',
  'Request Leave': 'تقديم طلب إجازة',
  'Employee': 'الموظف',
  'Duration': 'المدة',
  'Reason': 'السبب',
  'Actions': 'الإجراءات',
  'Approve': 'اعتماد',
  'Reject': 'رفض',
  'Processed': 'تمت المعالجة',
  'No Leave Requests': 'لا توجد طلبات إجازة',
  'No leave data available matching your search criteria.': 'لا توجد بيانات إجازات تطابق معايير البحث الحالية.',
  'New Leave Request': 'طلب إجازة جديد',
  'Start Date': 'تاريخ البداية',
  'End Date': 'تاريخ النهاية',
  'Cancel': 'إلغاء',
  'Submit Request': 'إرسال الطلب',
  'Loading requests...': 'جاري تحميل الطلبات...',
  'No reason provided': 'لم يتم إدراج سبب',
  'My Attendance': 'سجل حضوري',
  'Clock In': 'تسجيل الدخول',
  'Clock Out': 'تسجيل الخروج',
  'Date': 'التاريخ',
  'Total Hours': 'إجمالي ساعات العمل',
  'Working': 'على رأس العمل',
  'Completed': 'مكتمل',
  'View All': 'عرض الكل',
  'Today': 'اليوم',
  'My Salary History': 'سجل رواتبي السابقة',
  'All Salaries': 'جميع مسيرات الرواتب',
  'Month': 'الشهر',
  'Year': 'السنة',
  'Base Salary': 'الراتب الأساسي',
  'Allowances': 'البدلات',
  'Deductions': 'الاستقطاعات',
  'Net Pay': 'صافي الراتب',
  'Download Payslip': 'تحميل مسير الراتب (PDF)',
  'All Employees': 'جميع الكوادر',
  'Add Employee': 'إضافة موظف جديد',
  'Search employees...': 'البحث في سجل الموظفين...',
  'ID': 'الرقم الوظيفي',
  'Name': 'الاسم',
  'Email': 'البريد الإلكتروني',
  'Phone': 'رقم الهاتف',
  'Department': 'القسم الإداري',
  'Active': 'على رأس العمل',
  'Inactive': 'غير نشط / مستقيل',
  'Edit': 'تعديل',
  'Delete': 'حذف',
  'Export to Excel': 'تصدير بصيغة Excel',
  'Download Report': 'تنزيل تقرير مفصل',
  'Showing': 'عرض',
  'of': 'من أصل',
  'entries': 'سجلات',
  'to': 'إلى',
  'Previous': 'السابق',
  'Next': 'التالي',
  'Loading...': 'جاري التحميل...',
  'No Data': 'لا تتوفر بيانات',
  'Are you sure?': 'هل أنت متأكد من هذا الإجراء؟',
  'Success': 'تمت العملية بنجاح',
  'Error': 'حدث خطأ في النظام',
  'Save Changes': 'حفظ التغييرات',
  'Close': 'إغلاق',
  'Role': 'الدور الوظيفي (الصلاحيات)',
  'Account Details': 'تفاصيل الحساب والنظام',
  'Permissions': 'الصلاحيات الممنوحة',
  'Employee Management': 'إدارة شؤون الموظفين',
  'Payroll Access': 'صلاحية الوصول لمسيرات الرواتب',
  'Personal Details': 'البيانات الشخصية',
  'Hire Date': 'تاريخ التعيين',
  'Profile Not Linked': 'الحساب غير مرتبط بملف موظف',
  'Edit Profile': 'تعديل بيانات الحساب',
  'Contact Information': 'معلومات التواصل',
  'Change Password': 'تغيير كلمة المرور',
  'Current Password': 'كلمة المرور الحالية',
  'New Password': 'كلمة المرور الجديدة',
  'Confirm New Password': 'تأكيد كلمة المرور الجديدة',
  'System Admin': 'مدير النظام',
  'First Name': 'الاسم الأول',
  'Last Name': 'اسم العائلة',
  'Position': 'المسمى الوظيفي',
  'Join Date': 'تاريخ الالتحاق',
  'Save Employee': 'حفظ بيانات الموظف',
  'All Departments': 'جميع الأقسام الإدارية',
  'Add Department': 'إنشاء قسم إداري',
  'Department Name': 'اسم القسم الإداري',
  'Description': 'الوصف أو الملاحظات',
  'All Positions': 'جميع المسميات الوظيفية',
  'Add Position': 'إضافة مسمى وظيفي',
  'Position Title': 'عنوان المسمى الوظيفي',
  'Welcome to Kawadir': 'أهلاً بك في نظام كوادر',
  'Login to your account': 'تسجيل الدخول إلى حسابك',
  'Password': 'كلمة المرور',
  'Login': 'تسجيل الدخول',
  'Email Address': 'عنوان البريد الإلكتروني',
  'No Employees Found': 'لم يتم العثور على أية موظفين يطابقون بحثك',
  'Bonus & Penalty': 'المكافآت والاستقطاعات',
  'Meetings & Interviews': 'الاجتماعات والمقابلات',
  'Manage schedules and appointments': 'إدارة المواعيد وجداول الاجتماعات',
  'Schedule Meeting': 'جدولة اجتماع جديد',
  'Title / Subject': 'موضوع أو عنوان الاجتماع',
  'Date & Time': 'التاريخ والوقت',
  'Title': 'العنوان',
  'Organizer': 'الجهة المنظمة',
  'System': 'إشعار نظام',
  'Done': 'تم التنفيذ',
  'Cancel Meeting': 'إلغاء الاجتماع',
  'Join Meeting': 'الانضمام للاجتماع',
  'No meetings found.': 'لا توجد اجتماعات مجدولة حالياً.',
  'Select Employee': 'تحديد الموظف المعني',
  'Time': 'وقت التنفيذ',
  'Reason / Notes': 'المبررات أو الملاحظات',
  'Schedule': 'اعتماد الجدولة',
  'AI Assistant': 'المساعد الذكي (AI)',
  'View and manage employee payroll records': 'استعراض وإدارة سجلات الرواتب والأجور للكوادر',
  'Search by name, ID, or amount...': 'ابحث عبر الاسم، أو الرقم الوظيفي، أو المبلغ المالي...',
  'All Years': 'جميع السنوات المالية',
  'All Months': 'جميع الأشهر',
  'January': 'يناير (01)',
  'February': 'فبراير (02)',
  'March': 'مارس (03)',
  'April': 'أبريل (04)',
  'May': 'مايو (05)',
  'June': 'يونيو (06)',
  'July': 'يوليو (07)',
  'August': 'أغسطس (08)',
  'September': 'سبتمبر (09)',
  'October': 'أكتوبر (10)',
  'November': 'نوفمبر (11)',
  'December': 'ديسمبر (12)',
  'My Salaries': 'سجلات الرواتب الخاصة بي',
  'Add Salary': 'صرف راتب لموظف',
  'Edit Salary Record': 'تعديل تفاصيل الراتب',
  'Add New Salary': 'إدراج راتب جديد',
  'Meetings': 'الاجتماعات',
  'Urgent': 'عاجل جداً',
  'High': 'أهمية قصوى',
  'Normal': 'اعتيادي',
  'Company Announcements': 'إعلانات وتعاميم الشركة',
  'active announcement(s)': 'تعميم نشط',
  'Pending Approvals': 'الطلبات بانتظار الاعتماد',
  'Export to PDF': 'تصدير كملف PDF',
  'hrs': 'ساعات',
  'JD': 'د.أ',
  'Post': 'نشر التعميم',
  'Join': 'انضمام',
  'Jan': 'يناير',
  'Feb': 'فبراير',
  'Mar': 'مارس',
  'Apr': 'أبريل',
  'May_short': 'مايو',
  'Jun': 'يونيو',
  'Jul': 'يوليو',
  'Aug': 'أغسطس',
  'Sep': 'سبتمبر',
  'Oct': 'أكتوبر',
  'Nov': 'نوفمبر',
  'Dec': 'ديسمبر',
  'Add Fingerprint Login': 'تفعيل بصمة الدخول',
  'Fingerprint Added': 'تم اعتماد بصمة الدخول',
  'Sign in with Fingerprint': 'الدخول عبر البصمة المعتمدة',
  'All Employees Attendance': 'سجل الحضور والانصراف العام للكوادر',
  'Overview of all employees clock-in and clock-out records': 'نظرة شمولية لسجلات وتواقيت حضور وانصراف الموظفين',
  'Back to Employees': 'العودة لقائمة الموظفين',
  'Per page': 'عدد السجلات بالصفحة',
  'Employee Attendance Tracking': 'تتبع الحضور والانصراف للموظفين',
  'My Attendance Tracking': 'متابعة سجل حضوري',
  'Monitor all employees daily clock-in and clock-out records': 'مراقبة سجلات الحضور والانصراف اليومية لجميع الكوادر',
  'Monitor your daily clock-in and clock-out records': 'متابعة سجلات بصمة الدخول والخروج الخاصة بك',
  'Open session from': 'جلسة عمل مفتوحة منذ',
  'Click Clock Out to close it.': 'يرجى تسجيل الخروج لإنهاء الجلسة المعلقة.',
  'Shift Completed': 'تم إكمال مناوبة العمل بنجاح',
  'Filter': 'تصفية النتائج',
  'Loading attendance data...': 'جاري استرجاع بيانات الحضور والانصراف...',
  'No attendance records available yet matching your criteria.': 'لا تتوفر حالياً بيانات حضور تطابق خيارات التصفية المطلوبة.',
  'Register New User': 'إنشاء حساب مستخدم جديد بالنظام',
  'Create secure system credentials and assign appropriate roles for new employees.': 'إصدار بيانات دخول آمنة وتعيين الصلاحيات المناسبة للموظفين الجدد.',
  'Username': 'اسم المستخدم (تسجيل الدخول)',
  'System Role': 'الصلاحيات الوظيفية (الدور بالنظام)',
  'Select Role...': 'يرجى تحديد الدور...',
  'Registering...': 'جاري إنشاء الحساب...',
  'Create Account': 'اعتماد وإنشاء الحساب',
  'No announcements at this time.': 'لا توجد تعاميم أو إعلانات إدارية في الوقت الحالي.',
  'Post Announcement': 'إصدار تعميم إداري',
  'e.g., Company Holiday': 'مثال: عطلة رسمية للشركة',
  'Content': 'نص التعميم',
  'Write your announcement here...': 'اكتب تفاصيل التعميم أو الإعلان هنا...',
  'Priority': 'درجة الأهمية',
  'Expiry Date': 'تاريخ انتهاء صلاحية التعميم',
  'Optional': 'اختياري',
  'General Announcement (All Employees)': 'تعميم عام لجميع موظفي الشركة',
  'Select Target Employees': 'تحديد الموظفين المعنيين بالتعميم',
  'Manage organizational departments and view their employee structures': 'إدارة الأقسام الإدارية والاطلاع على الهياكل التنظيمية للكوادر',
  'Delete Picture': 'إزالة الصورة الشخصية',
  'Manage and track all company employees': 'إدارة شؤون الموظفين ومتابعة الكوادر البشرية بالشركة',
  'Upcoming Events & Birthdays': 'الفعاليات القادمة وأعياد ميلاد الموظفين',
  'Upcoming Events & Occasions': 'المناسبات والفعاليات القادمة',
  'Stay updated on birthdays and company events': 'ابق على اطلاع دائم بأعياد ميلاد الكوادر وفعاليات الشركة',
  'Add Event': 'إدراج مناسبة أو فعالية',
  'Loading events...': 'جاري جلب بيانات الفعاليات...',
  'No upcoming events': 'لا توجد فعاليات مجدولة',
  'There are no events scheduled for the next 60 days.': 'لا تتوفر أية فعاليات أو مناسبات خلال الـ 60 يوماً القادمة.',
  'Add New Event': 'إضافة فعالية مؤسسية جديدة',
  'Event Title': 'عنوان الفعالية / المناسبة',
  'Event Date': 'تاريخ التنفيذ',
  'Saving...': 'جاري الحفظ...',
  'Save Event': 'اعتماد وحفظ الفعالية',
  'Leave Automated Reset Settings': 'إعدادات إعادة ضبط أرصدة الإجازات برمجياً',
  'Reset Date Schedule': 'جدولة موعد إعادة الضبط السنوي',
  'Reset Month': 'شهر التصفير',
  'Reset Day': 'يوم التصفير',
  'Default Balances (Days)': 'الأرصدة الافتراضية (بالأيام)',
  'Last automatic reset was on:': 'آخر عملية إعادة ضبط مبرمجة تمت بتاريخ:',
  'Save Settings': 'اعتماد إعدادات النظام',
  'Select one or more employees to schedule a group meeting': 'تحديد الكوادر المعنية لجدولة اجتماع جماعي أو فردي',
  'View and manage your personal account details': 'استعراض وإدارة بيانات حسابك الشخصي والوظيفي',
  'Change Picture': 'تحديث الصورة الشخصية',
  'Pending Approval': 'قيد الاعتماد الإداري',
  'Awaiting HR review': 'بانتظار مراجعة إدارة الموارد البشرية',
  'Fingerprint Logins': 'سجلات الدخول الحيوي (البصمة)',
  'Manage employee deductions and allowances before payroll': 'إدارة وتوجيه الاستقطاعات والبدلات المالية قبل استصدار المسيرات',
  'Add Adjustment': 'إدراج حركة مالية',
  'Apply To': 'تطبيق الحركة على',
  'Type': 'نوع الحركة (بدل/خصم)',
  'Amount (JD)': 'القيمة المالية (د.أ)',
  'Save Adjustment': 'اعتماد الحركة المالية',
  'Profile Picture Approvals': 'اعتمادات تحديث الصور الشخصية',
  'Review and approve or reject pending profile picture requests': 'مراجعة البت في طلبات تحديث الصور الشخصية للكوادر',
  'All Caught Up!': 'تم إنجاز كافة المهام!',
  'There are no profile picture requests at this time.': 'لا توجد طلبات معلقة لتحديث الصور الشخصية حالياً.',
  'Profile Picture Requests': 'طلبات تحديث الصورة الشخصية',
  'Current Picture': 'الصورة الحالية المُعتمدة',
  'Requested Picture': 'الصورة الجديدة المُقترحة',
  'Manage company job titles and roles': 'إدارة المسميات الوظيفية والأدوار المهنية للكوادر',
  'Job Title': 'المسمى الوظيفي',
  'Salary Range (Min - Max)': 'النطاق المالي للأجور (الأدنى - الأعلى)',
  'No positions defined in the system.': 'لم يتم إدراج أية مسميات وظيفية في النظام حتى الآن.',
  'Modify Position': 'تعديل مواصفات المسمى الوظيفي',
  'Create New Position': 'استحداث مسمى وظيفي',
  'Approve Salaries': 'الاعتماد النهائي للمسيرات',
  'Generate Payroll': 'استصدار مسيرات الرواتب',
  'Payroll': 'نظام مسيرات الرواتب والأجور',
  'Events & Birthdays': 'المناسبات وأعياد الميلاد'
};

const finalMap = {};
for (const k of allKeys) {
  if (dictionary[k]) {
    finalMap[k] = dictionary[k];
  } else {
    finalMap[k] = k;
  }
}

let fileContent = 'export const TRANSLATIONS: { [key: string]: { en: string; ar: string } } = {\n';
for (const k of Object.keys(finalMap).sort()) {
  const en = k.replace(/'/g, "\\'");
  const ar = finalMap[k].replace(/'/g, "\\'");
  fileContent += `  '${en}': { en: '${en}', ar: '${ar}' },\n`;
}
fileContent += '};\n';

fs.writeFileSync('src/app/core/i18n/translations.ts', fileContent, 'utf8');
console.log('Translations updated successfully.');
