// <auto-generated />
using System;
using HRMS_GradProject.AppContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HRMS_GradProject.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20260405215151_firstinitDB")]
    partial class firstinitDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HRMS_GradProject.Entity.Attendance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<TimeOnly>("clock_in")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly>("clock_out")
                        .HasColumnType("time without time zone");

                    b.Property<DateTime>("date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("employeeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("employeeId");

                    b.ToTable("Attendances");
                });

            modelBuilder.Entity("HRMS_GradProject.Entity.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("HRMS_GradProject.Entity.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("integer");

                    b.Property<int?>("PositionId")
                        .HasColumnType("integer");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("firstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("hireDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("isActive")
                        .HasColumnType("boolean");

                    b.Property<string>("lastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("phoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("userId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("PositionId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("HRMS_GradProject.Entity.LeaveRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("approved_by")
                        .HasColumnType("integer");

                    b.Property<int>("employeeId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("endDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("leaveType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("rejectionReason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("startDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("approved_by");

                    b.HasIndex("employeeId");

                    b.ToTable("LeaveRequests");
                });

            modelBuilder.Entity("HRMS_GradProject.Entity.Position", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("integer");

                    b.Property<decimal>("salary_max")
                        .HasColumnType("numeric");

                    b.Property<decimal>("salary_min")
                        .HasColumnType("numeric");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Positions");
                });

            modelBuilder.Entity("HRMS_GradProject.Entity.Salary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Month")
                        .HasColumnType("integer");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.Property<decimal>("allowances")
                        .HasColumnType("numeric");

                    b.Property<decimal>("base_amount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("deductions")
                        .HasColumnType("numeric");

                    b.Property<decimal>("effective_date")
                        .HasColumnType("numeric");

                    b.Property<int>("employeeId")
                        .HasColumnType("integer");

                    b.Property<decimal>("gross_amount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("net_amount")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("employeeId");

                    b.ToTable("Salaries");
                });

            modelBuilder.Entity("HRMS_GradProject.Entity.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("HRMS_GradProject.Entity.Attendance", b =>
                {
                    b.HasOne("HRMS_GradProject.Entity.Employee", "employee")
                        .WithMany("Attendances")
                        .HasForeignKey("employeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("employee");
                });

            modelBuilder.Entity("HRMS_GradProject.Entity.Employee", b =>
                {
                    b.HasOne("HRMS_GradProject.Entity.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HRMS_GradProject.Entity.Position", null)
                        .WithMany("Employees")
                        .HasForeignKey("PositionId");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("HRMS_GradProject.Entity.LeaveRequest", b =>
                {
                    b.HasOne("HRMS_GradProject.Entity.User", "user")
                        .WithMany("LeaveRequests")
                        .HasForeignKey("approved_by")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HRMS_GradProject.Entity.Employee", "employee")
                        .WithMany("leaveRequests")
                        .HasForeignKey("employeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("employee");

                    b.Navigation("user");
                });

            modelBuilder.Entity("HRMS_GradProject.Entity.Position", b =>
                {
                    b.HasOne("HRMS_GradProject.Entity.Department", "Department")
                        .WithMany("Positions")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("HRMS_GradProject.Entity.Salary", b =>
                {
                    b.HasOne("HRMS_GradProject.Entity.Employee", "employee")
                        .WithMany("Salaries")
                        .HasForeignKey("employeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("employee");
                });

            modelBuilder.Entity("HRMS_GradProject.Entity.User", b =>
                {
                    b.HasOne("HRMS_GradProject.Entity.Employee", "Employee")
                        .WithOne("User")
                        .HasForeignKey("HRMS_GradProject.Entity.User", "EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("HRMS_GradProject.Entity.Department", b =>
                {
                    b.Navigation("Employees");

                    b.Navigation("Positions");
                });

            modelBuilder.Entity("HRMS_GradProject.Entity.Employee", b =>
                {
                    b.Navigation("Attendances");

                    b.Navigation("Salaries");

                    b.Navigation("User")
                        .IsRequired();

                    b.Navigation("leaveRequests");
                });

            modelBuilder.Entity("HRMS_GradProject.Entity.Position", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("HRMS_GradProject.Entity.User", b =>
                {
                    b.Navigation("LeaveRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
